- Vagrantfile
- playbooks/playbook.yml
- playbooks/run_semaphore
Get the vagrant deploy working out of the box:
* fixed copy of the credentials in playbook
* run with `node` command instead of `grunt`
> fix vagrant install to run out of the box

- lib/runner.js
- lib/scripts/pullGit.sh
Hi,
I replaced the '/root/' with the actual home of the running user. So one can start semaphore as a normal user. 
Fixes #39
> Replace root home with home of the semaphore user

- lib/config.js
If there are any users in the DB skip the creation of the default admin.
When user starts the app from scratch the default admin is created. If the user adds another admin and deletes the default user,
the default admin will not be created.
If there is the case that the user deletes all admins (including the one he is using right now) the default admin is created again.
This fixes bug #48 which can be a security issue for open deploys of semaphore application.
> If users in db don't create default user (fixes #48)

- Dockerfile
Every job run runner.js leaves a "defunct" pullGit.sh. Please see https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ for details.
> Added `tini' to reap zombies - a well-known issue with PID 1 process.

- lib/models/Job.js
- lib/routes/job/job.js
- lib/routes/job/jobs.js
- lib/runner.js
- lib/views/playbook/job.jade
- lib/views/playbook/jobs.jade
Similar to extra_vars, I created exec_options which will be added to ansible_playbook  [options]. Currently I am using this to view details logs, but it can be generic and all ansible_playbook options can  be sent over. Please include this in master if you find it useful. 
Changes: I changed Job model, job edit template, jobs listing template, and save() and add() methods where Job gets persisted. Also changed runner.js to apply the changes while invoking executable.
> Inject ansible-playbook executable options using job definition

- api/tasks/runner.go
add --recursive to support download playbooks which uses git submodule
related issue : #181
> add missing " --recursive"

- Deploy/docker-compose.yml
- Dockerfile
- semaphore-startup.sh
Changes done:
- Updated base image from Fedora to Alpine. Reduces the image size from 436MB to 130 MB.
- Moved the docker file and startup script to the root directory
- Removed the ENV variables out of the docker file and into the compose file
- Pointed the compose file to the future image on docker hub
- Adjusted the compose file to use Version 2 syntax, as recommended by Docker
This should make it doable to have an image on Dockerhub to use for people while keeping the functionality of the compose file to create a local stack.
> Prepare repo for automated build on Dockerhub

- api/tasks/runner.go
Correct issue [119](https://github.com/ansible-semaphore/semaphore/issues/119).
With this, you just have to specify the tag or branch at the end of url in the playbook repository definition.
`git://github.com:userspace/reponame.git#tag|branch`
_Full disclosure : I am not a golang dev ;)_
> add support for git repo tags or branches 

- public/html/projects/dashboard.jade
Changed text colors for task statuses `waiting` and `running` to less confusing colors
> Task history: changed status colors

- api/tasks/runner.go
- make.sh
> Pass OS environment variables to Ansible

- CONTRIBUTING.md
* Add nodemon installation
* cd to github.com/ansible-semaphore/semaphore instead of github.com/ansible-semaphore (because `git clone` creates `semaphore` folder)
> Small documentation improvements

- util/upgrade.go
google/go-github broke the api of their functions with google/go-github@23d6cb9
This PR adds the context `context.TODO()` to the call of `gh.Repositories.ListReleases` which is meant to be used "when it's unclear which Context to use or it is not yet available (because the surrounding function has not yet been extended to accept a Context parameter)" (citing https://godoc.org/context)  
I chose this way because AFAIK we don't have much use of the [`context` package](https://golang.org/pkg/context/).  
fixes #267
> fix api breaking of google/go-github

- public/html/projects/templates/add.jade
UI improvements for https://github.com/ansible-semaphore/semaphore/issues/261
> Add/Update Template dialog: Add Template ID field, mark some fields as required

- .gitignore
- api-docs.yml
- api/projects/inventory.go
implement #279 
add content to response of post /project/{project_id}/inventory
> add content to response of post /project/{project_id}/inventory

- api/projects/templates.go
Fix for https://github.com/ansible-semaphore/semaphore/issues/171
> Provide NULL instead of empty string, when Extra CLI Arguments was deleted

- Dockerfile
- semaphore-startup.sh
* Improve the Dockerfile build speed and space by flattening all to one layer
* Added env var in Dockerfile for version and arch of semaphore
> Improve the docker entrypoint and dockerfile

- public/css/semaphore.less
- public/html/projects/container.pug
- public/html/projects/templates/list.pug
- public/js/controllers/projects/templates.js
> Add copy button to "Task Templates" page

- api/tasks/runner.go
Currently, there is no fast way to check how (and which) last tasks was executed, especially if they were called from different projects. I added task template name and status (success/error) to the Event.description field (and dashboard log).
> Add more verbosity about tasks to the Events description

- api-docs.yml
- api/projects/environment.go
- api/projects/inventory.go
- api/projects/keys.go
- api/projects/repository.go
- api/projects/templates.go
- api/projects/users.go
- public/js/controllers/projects/environment.js
- public/js/controllers/projects/inventory.js
- public/js/controllers/projects/keys.js
- public/js/controllers/projects/repositories.js
- public/js/controllers/projects/templates.js
- public/js/controllers/projects/users.js
> Rearrange list of Task Template, Inventory, Environment, Team in UI

- api/login.go
- api/users.go
- db/migrations/v2.3.0.sql
- models/User.go
- public/html/users/user.pug
- util/config.go
Algorithm: https://github.com/ansible-semaphore/semaphore/issues/118#issuecomment-288957589
I have some doubts about my code:
- How can I do proper logging for LDAP errors/messages? Currently, I use 'dumb' `println`, because I can't see any logs except Gin logging
- We do not need to edit username and password for LDAP users. I just make this fields read-only on frontend (but editing still possible via API). Should I add additional validation, or we may keep this way for editing?
- I added the migration to the same file - `2.3.0.sql` because 2.3.0 isn't released. Is it ok?
> Simple authorization via LDAP

- api/tasks/http.go
- api/tasks/logging.go
- db/migrations/v2.2.1.sql
- util/util_test.go
* Add id column to task__output table (fix the queries for it)
* Print error message in case of database error(s)
I tried to fix the `util` test but failed in doing so..
***
Should the PR target the `develop` or `master` branch ? (This PR is targeted at the `develop` branch)
> Fix the primary key creation queries in v2.2.1 migration

- api/projects/templates.go
When updating a template with empty "Extra CLI Arguments" field, the
template.Arguments pointer becomes nil. The previous check whether this
variable is the empty string fails if it is already nil.
The fix introduces a lazy nil check before the empty string-check.
Solves #337
> Fix nil pointer dereference when updating Template. Solves #337

- api/tasks/pool.go
- api/tasks/runner.go
- util/config.go
Two different concurrency modes are implemented, and is enabled by
setting "concurrency_mode" in the config file to either "project" or "node".
When "project" concurrency is enabled, tasks will run in parallel if and
only if they do not share the same project id, with no regard to the
nodes/hosts that are affected.
When "node" concurrency is enabled, a task will run in parallel if and
only if the hosts affected by tasks already running does not intersect
with the hosts that would be affected by the task in question.
If "concurrency_mode" is not specified, no task will start before the
previous one has finished.
The collision check is based on the output from the "--list-hosts"
argument to ansible, which uses the hosts specified in the inventory.
Thus, if two different hostnames are used …
> Allow concurrency for tasks that does not collide. Fixes #365

- api-docs.yml
- api/events.go
- api/router.go
- api/tasks/http.go
- public/html/dashboard.pug
- public/html/projects/dashboard.pug
- public/js/controllers/dashboard.js
- public/js/controllers/projects/dashboard.js
Fix for https://github.com/ansible-semaphore/semaphore/issues/367
I created a simple solution. I added the limit of 200 items to activity and tasks lists and button for all events/tasks loading.
In my case (about 6000 events in the database) this decreased page load time from 15 to 2 seconds.
> Limit activity and tasks lists in dashboards

- api/tasks/logging.go
Fix for https://github.com/ansible-semaphore/semaphore/issues/393
bufio.Reader smarter than bufio.Scanner, it can work with big strings, which not fit in the buffer:
https://golang.org/pkg/bufio/#Scanner
> Scanning stops unrecoverably at EOF, the first I/O error, or a token too large to fit in the buffer. When a scan stops, the reader may have advanced arbitrarily far past the last token. Programs that need more control over error handling or large tokens, or must run sequential scans on a reader, should use bufio.Reader instead.
This PR doesn't provide a full solution for crashes on big outputs. We still need to fix https://github.com/ansible-semaphore/semaphore/issues/132, because displaying a big diff (or a content of the file with many lines) cause an enormous number of database …
> Use bufio.Reader instead of bufio.Scanner for task logging

- public/html/projects/templates/list.pug
- public/js/controllers/projects/templates.js
Add ability to hide templates in the list.
This commit:
- adds button "hide" to each row in the template list. 
- adds button "show hidden" on top of the template list to show hidden templates.
IDs of hidden templates stores to localStorage item "hidden-templates".
> feat(template): hidden templates

- public/html/projects/taskModal.pug
- public/js/controllers/projects/dashboard.js
Small improvement for https://github.com/ansible-semaphore/semaphore/issues/314
Now, we can get permalink to the task output (in JSON, unfortunately, I'm not so good in JS to create new page from scratch) directly from task log:
P.S. @matejkramny we miss you! :)
> add link to JSON task output in task info

- api/tasks/runner.go
fix for https://github.com/ansible-semaphore/semaphore/issues/441
I just moved `runGalaxy()` from `Task Run` to `Task Prepare` step. @Natanande, can you review it? This bug caused by task concurrency code
> Fix crash when new role added to requirements

- api/tasks/runner.go
I had an issue with Semaphore where trying to connect to a host that is not already in the known hosts list would ask you if you wished to add them to the known_hosts. This would cause semaphore to be unable to start any other task and a restart would be needed.
With this fix I simply attach a blank string as stdin to the playbook run command, which causes the host key verification to fail in this instance
> Fix stdIn hanging issue

- .gitignore
I found ```util/binddata.go``` in ```.gitignore``` but file isnt't deleted. I've deleted it.
Also added ```cli/semahore_*``` to gitignore.
> Add binaries to gitignore and remove binddata.go

- .gitignore
- Taskfile.yml
- public/html/admin.pug
- public/html/index.pug
- util/config.go
- util/version.go
- util/version_gen/generator.go
This is a proposal to replace the version.go file with a generated version, which is created at task compile time. This allows us to give every release of semaphore a unique ID by which we can identify it, which becomes more important once we start pushing out docker images for development builds, and it also makes it easier to identify what build you are actually running. It additionally adds the `--version` option to the semaphore cli, which will return the current version string and exit.
The version generator itself is really simple, it expects you to pass in a version string to it, and renders the file pretty much as before, therefore most of the actual logic happens in the taskfile to render a unique value. It uses the following logic:
If a tag exists on this commit then use it. …
> add version code generator

- public/html/projects/templates/add.pug
- public/js/app.js
- public/js/controllers/admin.js
- public/js/controllers/dashboard.js
- public/js/controllers/login.js
- public/js/controllers/projects/dashboard.js
- public/js/controllers/projects/edit.js
- public/js/controllers/projects/environment.js
- public/js/controllers/projects/inventory.js
- public/js/controllers/projects/keys.js
- public/js/controllers/projects/repositories.js
- public/js/controllers/projects/taskRunner.js
- public/js/controllers/projects/templates.js
- public/js/controllers/projects/users.js
- public/js/controllers/tasks.js
- public/js/controllers/user.js
- public/js/controllers/users.js
- public/js/factories/hostgroup.js
- public/js/factories/playbook.js
- public/js/routes/auth.js
- public/js/routes/project.js
- public/js/services/hostgroups.js
- public/js/services/identities.js
- public/js/services/jobs.js
- public/js/services/playbooks.js
- public/js/services/tasks.js
- public/js/services/user.js
- public/js/services/users.js
Update angularjs to v1.6, angular-ui to 2.5.
I replaced ```success/error``` blocks to ```then/catch``` because angular v1.6 isn't support it.
Please apply ```update-angular``` PR to ```semaphore-vendor``` before
> Update angularjs/angular-ui to last version

- util/config.go
- util/config_test.go
fix for #401 which ensures that the config contains a port value which is always prefixed with `:`
> fix port : prefix issues when building config data

- CONTRIBUTING.md
- README.md
- Taskfile.yml
- circle.yml
Proposal to deal with goreleaser on windows and linux. See #498 for context.
As this is actually quite a difficult issue to solve in an elegant way and `go get` with and without `/...` causes issues on different versions of linux (current implementation breaking on cirleci and fedora) and windows this PR proposes that we instead curl the binary and install it to `$GOPATH/bin`.
As curl is not possible on windows we unfortunately skip these steps for windows users and instead echo a warning that they must install the tool manually. Additionally this manual step information has been added in the contribution guide.
Please can you check the goreleaser install steps are skipped properly on windows when reviewing.
@fiftin - any thought or input? Is there some one-liner we could use in windows …
> skip goreleaser install on windows and warn

- web/public/js/controllers/projects/edit.js
- web/public/js/controllers/projects/environment.js
- web/public/js/controllers/projects/inventory.js
- web/public/js/controllers/projects/keys.js
- web/public/js/controllers/projects/repositories.js
> Fixed SweetAlert confirmation popup

- .circleci/config.yml
- .gitignore
- CONTRIBUTING.md
- README.md
- Taskfile.yml
- deployment/docker/Readme.md
- deployment/docker/dev/docker-compose.yml
- deployment/docker/prod/bin/install
- deployment/docker/prod/docker-compose.yml
This PR changes the way that circleci does it's builds, changing to use workflows. This needed to be done so that I could build and push the images to docker hub in a nicer way. It also resulted in some other changes:
* all steps of the tests now run in containers
* parts of the tests now run in parallel
* halves the time the tests take to run (now ~4mins)
* All pushes to the develop branch will generate a new docker image with the tag _develop_
* Pushes to master will create a new image with the tag _$tag_ and update the _latest_ tag as well
* In agreement with @Echobob and @matejkramny semaphore images will now be pushed to the docker namespace of ansiblesemaphore. So the official image will be **ansiblesemaphore/semaphore**
Test pipeline (without release steps) looks a bit like this, …
> circleci workflows and docker image build and push

- deployment/openshift/README.md
- deployment/openshift/template.yml
Working openshift template for semaphore deploys. Deleted the old PR as that branch was so far behind develop now.
Note that at the moment you will need to use the parameter ` -p SEMAPHORE_IMAGE_TAG=develop` or switch to the old repo when running `oc new-app semaphore` as we dont have a latest tag in the new repo yet.
> openshift template

- .circleci/config.yml
- deployment/docker/ci/docker-compose.yml
pins mysql to 5.6 so that 8 is not chosen when testing as it results in breakage
> pin mysql to 5.6
