README.md, lib/config.js, lib/credentials.default.json
=> Extend credintials.json from environment

.gitignore, lib/routes/index.js, lib/routes/user/user.js, lib/routes/user/users.js, lib/views/layout.jade, lib/views/user/add.jade, lib/views/user/list.jade, lib/views/user/view.jade, public/js/controllers/user/add.js, public/js/controllers/user/user.js, public/js/controllers/user/users.js, public/js/factories/user.js, public/js/routes/routes.js, public/js/routes/users.js, public/js/services/users.js
=> User management

lib/routes/playbook/playbooks.js
This commit is to resolve #28 
Replacing credentials by identity.
=> Fix the issue about identity on playbook creation

lib/models/Host.js, lib/routes/host/host.js, lib/runner.js, lib/views/playbook/hosts.jade
Based on https://github.com/ansible-semaphore/semaphore/pull/26
I created a 'vars' field in the form so the would be kept in DB
and used in the inventory creation
=> Adding host variables to db

lib/models/Job.js, lib/routes/index.js, lib/routes/job/job.js, lib/routes/job/jobs.js, lib/routes/playbook/playbook.js, lib/runner.js, lib/views/playbook/job.jade, lib/views/playbook/jobs.jade, public/js/controllers/playbook/job.js, public/js/controllers/playbook/jobs.js, public/js/factories/job.js, public/js/routes/playbooks.js, public/js/services/job.js
You can edit a job from the job list of a playbook and add some extra vars to be used when running the playbook.
=> Gives the ability to Edit a Job and Implements extra-vars

public/css/semaphore.less
Probably a much better way to do this.
=> Rotate the octocat on the github corner

api/tasks/http.go, db/migrations/v1.7.0.sql, db/versionHistory.go, models/Task.go, public/html/projects/dashboard.jade, public/html/projects/taskModal.jade, public/js/controllers/projects/taskRunner.js
And show user name in task information view.
[![https://gyazo.com/d64fef16814b29c0a4df9bec9de9b337](https://i.gyazo.com/d64fef16814b29c0a4df9bec9de9b337.png)](https://gyazo.com/d64fef16814b29c0a4df9bec9de9b337)
[![https://gyazo.com/3736da4884356a764a19428ac0d8b5e3](https://i.gyazo.com/3736da4884356a764a19428ac0d8b5e3.png)](https://gyazo.com/3736da4884356a764a19428ac0d8b5e3)
I want to know, who executed tasks.
=> Save task executed user's ID in database.

api/tasks/runner.go
I want to see the repository url in log file
=> Show repository url in log

api/tasks/runner.go, db/migrations/v1.8.0.sql, db/versionHistory.go, models/Task.go, public/html/projects/createTaskModal.jade, public/js/controllers/projects/taskRunner.js
Added following button.
[![https://gyazo.com/7600905fa746ca81eed89a66fd7abfdd](https://i.gyazo.com/7600905fa746ca81eed89a66fd7abfdd.png)](https://gyazo.com/7600905fa746ca81eed89a66fd7abfdd)
If user clicked this button, ansible-semaphore runs ansible-player with `--check` option.
=> Added dry_run button. close #152

CONTRIBUTING.md, api-docs.yml, api/projects/templates.go, db/migrations/v.1.9.0.sql, make.sh, models/Template.go, public/html/projects/templates/add.jade, public/html/projects/templates/list.jade
More information at https://github.com/ansible-semaphore/semaphore/issues/188
=> Added an `Alias` Field for Task template. 

CONTRIBUTING.md, api-docs.yml, api/projects/templates.go, db/migrations/v.1.9.0.sql, make.sh, models/Template.go, public/html/projects/templates/add.jade, public/html/projects/templates/list.jade
PR for https://github.com/ansible-semaphore/semaphore/issues/213 and https://github.com/ansible-semaphore/semaphore/issues/188
Please close #224, the patches are the same :S
=> Provide a better contributing guide and use of pug instead of jade. Check #213.

public/js/controllers/projects/environment.js, public/js/controllers/projects/inventory.js, public/js/controllers/projects/repositories.js, public/js/controllers/projects/users.js
=> Erorr -> Error

Dockerfile
As it doesn't come with Alpine or either of the other packages.
=> Add ssh client to dockerfile

api-docs.yml
/project/{project_id}/template   ==>   /project/{project_id}/templates
=> fix error api-doc route

public/js/controllers/projects/templates.js
=> Reload on modal dismiss

api/tasks/http.go, api/tasks/runner.go, public/html/projects/dashboard.jade
Small UI improvment for https://github.com/ansible-semaphore/semaphore/issues/253
Before:
After:
=> Add task template names to dashboard

api/tasks/runner.go, public/html/projects/keys/add.pug
=> Added SSH certificate support

api/auth.go, cli/main.go, models/Event.go
Fix https://github.com/ansible-semaphore/semaphore/issues/276
=> Use UTC_TIMESTAMP instead of NOW

CONTRIBUTING.md
=> add missing package and command

db/migrations/v2.2.1.sql, db/versionHistory.go
This adds primary keys to the database tables.
This closes #293
=> Added primary keys to the existing tables

api-docs.yml
=> Fix duplicated mapping key mapping key "Task"

api/tasks/alert.go, api/tasks/runner.go, util/config.go
Hello, everyone! 
After adding email alerts I was found that this is not the optimal choice and I added Telegram alerts too. :)
Logic is the same: if global telegram alerts are configured AND individual project alerts is checked - alert about failed task in the project will be sent.
BTW, here is an easy way to add any other alerting channels, like Slack or so.
=> Telegram alerts

semaphore-startup.sh
I think we should create link to config `/etc/semaphore/semaphore_config.json` after we generated original one
=> Fixes #320

api/tasks/alert.go
Fix for https://github.com/ansible-semaphore/semaphore/issues/329
=> fix alert templates after 5bcb34e

api/login.go
Fix for https://github.com/ansible-semaphore/semaphore/issues/335
I also added comments to the code, for the better process understanding
=> Fix login logic when ldap is enabled

api-docs.yml, api/router.go, api/tasks/http.go
Reference issue #356
Get a single task
=> Get tasks details

api/projects/project.go, api/tasks/alert.go, api/tasks/runner.go, db/Project.go, db/migrations/v2.4.0.sql, db/versionHistory.go, public/html/projects/edit.pug, public/js/controllers/projects/edit.js, public/js/factories/project.js
Fixes for https://github.com/ansible-semaphore/semaphore/issues/343
=> Add option for per-project telegram alert to different chats

api/login.go
This should fix issues in the login logic.
@strangeman can you test & review?
=> Rewrite login functions

cli/main.go
=> Typo fix main.go

public/js/controllers/projects/dashboard.js
fixes https://github.com/ansible-semaphore/semaphore/issues/372
Also, I fixed negative Task duration in Task history:
=> fix wrong data format in Project activity log

CONTRIBUTING.md
@matejkramny Hi, any one can review this PR?
=> Update CONTRIBUTING.md with a note for Windows.

README.md
Guys, I wrote a guide for Semaphore UI with screenshots. If external resources isn't allowed - we may move it to the Semaphore Wiki
=> Add link to UI Walkthrough

api-docs.yml
=> fixed wrong status code for created projects

make.sh, public/bundle.json, public/css/semaphore.less, public/html/projects/taskModal.pug, public/js/app.js, public/js/controllers/projects/taskRunner.js, util/bindata.go
This PR changes the modal log positioning adding a scroll to the log box.
=> Scroll enabled Task Log. Do not mix output from different tasks. Fixes #353 #322

public/html/projects/taskModal.pug
fix for https://github.com/ansible-semaphore/semaphore/issues/468
=> allow copy from task log text area

README.md, Taskfile.yml, circle.yml
W.I.P until i can get access to add a push hook to this repo to properly integrate it.
Also needs some work due to symlink issues when run in circleci :grimacing:
=> add codacy code review links, generate and export coverage info

web/resources/pug/projects/templates/add.pug
Fix this issues: https://github.com/ansible-semaphore/semaphore/issues/496, https://github.com/ansible-semaphore/semaphore/issues/493
=> Fix: Extra arguments are not being saved in task templates

api/tasks/runner.go
Fix for https://github.com/ansible-semaphore/semaphore/issues/495
=> Add stderr for `list-hosts` output

.circleci/config.yml
See #510 for reasons this fix was needed and did not appear before the merge to develop
=> update circle config to account for cache issue

Taskfile.yml, web/package.json
+ small windows-related fixes
Fix for https://github.com/ansible-semaphore/semaphore/issues/506
=> add local installation of fe tools, add relative paths to that tools

deployment/docker/prod/proxy/Dockerfile
Ending quote missing on author email-address
=> Quote missing in proxy dockerfile

Taskfile.yml, deployment/systemd/README.md, deployment/systemd/env, deployment/systemd/semaphore.service, deployment/systemd/util/install.sh, deployment/systemd/util/uninstall.sh
=> systemd example

.circleci/config.yml, .dredd/dredd.local.yml, .dredd/dredd.yml, .dredd/hooks/capabilities.go, .dredd/hooks/helpers.go, .dredd/hooks/main.go, CONTRIBUTING.md, Gopkg.lock, Taskfile.yml, api-docs.yml, api/api_test.go, api/projects/projects.go, api/projects/users.go, api/router.go, api/user.go, api/users.go, db/AccessKey.go, db/mysql.go, deployment/docker/Readme.md, deployment/docker/ci/Dockerfile, deployment/docker/ci/bin/install, deployment/docker/ci/docker-compose.yml, deployment/docker/ci/dredd.Dockerfile, deployment/docker/ci/dredd/entrypoint, deployment/docker/prod/bin/install
Sorry to drop another fairly large PR into the mix, but I hope you will agree this is worth it.
I've added [dredd](http://dredd.readthedocs.io/en/latest/index.html) to Semaphore as a way to test the api documentation for correctness, and changes leave the api in a working state.
Basically it takes the swagger spec, and tries all the calls against the API, validating that what it gets back matches. At the moment this only tests the 'happy path', but i can imagine adding a few more hooks in future that set up for tests around user access (logged out, admin etc...), or no results responses (some no results responses cause panics so it would also help us to introduce this test when dealing with #462)
I've had to write some hooks for the tests, to make sure that the correct things exist in the …
=> use dredd for api testing

web/public/js/controllers/users.js
=> Assign users response correctly

.goreleaser.yml
adds a maintainer to the package to stop warnings on install
=> add maintainer information

Taskfile.yml, Taskfile_windows.yml, web/package-lock.json, web/public/js/controllers/projects/repositories.js, web/public/js/controllers/users.js
I'm didn't fix bug #535 completely in previous PR. This PR fix it completely
=> Fix creating new user

deployment/docker/dev/docker-compose.yml, deployment/docker/prod/docker-compose.yml
update pins in dockerfiles for mysql
=> pin sql versions in all docker compose files

cli/main.go, util/config.go
fix for #538.
I guess this should be in 2.6.0 since adding a variable is not a patch action
=> add interface variable to settings
